
incremental: true

name: lemonbytes
author: Stan Lemon
title: lemonbytes by Stan Lemon
description: husband, dad, steelers fan and software engineer
baseurl: ""
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: /page/:num/
url: "https://stanlemon.net"
twitter_username: stanlemon
github_username: stanlemon
linkedin_username: stanlemon
google_analytics: UA-33072694-1

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
