# Site settings
title: Lemon Bytes
email: me@stanlemon.net
description: Husband, Dad, Steelers fan and Software Engineer at Pardot, a Salesforce company. My opinions are just mine!
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "page/:num/"
url: "http://stanlemon.net" # the base hostname & protocol for your site
twitter_username: stanlemon
github_username: stanlemon

# Build settings
markdown: kramdown
